### ISSUE TITLE
Question about add translation.

### ISSUE THREAD

**Issue by solitary-sails** [ow-mods/ow-mod-man#211]
I noticed there is a Chinese translation now. But I found you said in #36 that "wait until 1.0 to add more translations". Will the project now accept more new translations, or will it still have to wait for version 1.0?

**Comment by loco-choco** [comment]
The translations are more in a state of "you can add them, but all the text might change out of the blue, and then you need to do it again". @Bwc9876 can correct me, but after 1.0 they really aren't supposed to change, so if you do a translation, it should stick for a while.

**Comment by solitary-sails** [comment]
Thanks. I understand the situation now.

**Comment by Bwc9876** [comment]
> The translations are more in a state of "you can add them, but all the text might change out of the blue, and then you need to do it again". @Bwc9876 can correct me, but after 1.0 they really aren't supposed to change, so if you do a translation, it should stick for a while.

Yeah, we're getting pretty close to 1.0 and *most* of the text is finalized but you're still probably better off waiting.
