### ISSUE TITLE
Mod Manager Crashes at Launch

### ISSUE THREAD

**Issue by JefferyT51** [ow-mods/ow-mod-man#266]
### What Happened?

I've just installed the Mod Manager on my desktop (Windows 11).  But whenever I try to open the program, it immediately opens a new notepad doc with crash details (crash_log_[date]_[time]).  It shows the following message:

> The manager encountered a fatal error when starting: Runtime(CreateWebview(WebView2Error(WindowsError(Error { code: 0x80070002, message: The system cannot find the file specified. }))))

I'm unsure of how to proceed with this.  I didn't have this issue on my other system, but for some reason this one throws an error code and refuses to launch.  Any ideas on what the issue is?

### Package

Graphical Interface

### Platform

Windows

### Logs

The manager encountered a fatal error when starting: Runtime(CreateWebview(WebView2Error(WindowsError(Error { code: 0x80070002, message: The system cannot find the file specified. }))))

**Comment by Bwc9876** [comment]
Could you try making sure you have Edge installed? The manager utilizes its WebView2 component in order to render.

**Comment by Bwc9876** [comment]
Also try installing [the Evergreen Webview2 runtime bootstrapper](https://developer.microsoft.com/en-us/microsoft-edge/webview2/).

**Comment by JefferyT51** [comment]
I think you got it.  Unfortunately I removed Edge with a 'Windows Debloater Tool'.  So, that would explain the issue.  That is completely my fault.  Thank you for pointing the connection out.

Now to figure out how to put Edge back...
