### ISSUE TITLE
[Bug Report] Error when trying to start game while offline, start game stuck disabled

### ISSUE THREAD

**Issue by Raicuparta** [ow-mods/ow-mod-man#374]
### What Happened?

Press start game while offline, this happens:

![Screenshot 2024-01-22 153430](https://github.com/ow-mods/ow-mod-man/assets/3955124/cb9d7aea-0a10-405e-8dbc-815ae585e54c)

In this particular case I was connected to a network with no internet connection. Dunno why it's tying to connect to the db before playing the game.

Then start button is stuck disabled.

### Package

Graphical Interface

### Platform

Windows

**Comment by Bwc9876** [comment]
Probably this line: https://github.com/ow-mods/ow-mod-man/blob/3f9d37a7acaaaf4ed21428b6764e0ae19a26b294/owmods_gui/backend/src/commands.rs#L889-L890
