### ISSUE TITLE
Manager does not treat "dependency mods" differently from regular mods

### ISSUE THREAD

**Issue by Ixrec** [ow-mods/ow-mod-man#441]
### What Happened?

On the Discord I proposed:
> it might be nice if OWML had some special treatment for "dependency mods" that the user never asked for and only exist as a dep of something else, like displaying them less prominently or automatically toggling them when the mods using them are toggled

then to my total surprise, got told this is a thing it's already supposed to be doing.

So, well, it doesn't do any of that. At least not that I've ever seen. I've used many mods that had dependencies (even made my own mod that has a few), so if such a feature is supposed to exist I guess it must be buggy?

### Package

Graphical Interface

### Platform

None

**Comment by Bwc9876** [comment]
So just to recap what happened in the Discord. This functionality *does* exist (at least in terms of recursively disabling dependencies), however, it was specific to the CLI and disabled in the GUI. The plan is to add the option to also recursively disable deps.
