### ISSUE TITLE
[Bug Report] New Horizons Issues

### ISSUE THREAD

**Issue by Khascoil** [ow-mods/ow-mod-man#506]
### What Happened?

It appears that none of the mods related to using the New Horizons template that I've installed via the OWML want to work anymore. I have no idea what could have happened to cause this bug, and I thought perhaps that maybe some of the mods may have lost support or have been outdated to the point of non-existence or even perhaps conflicted with other mods, but a quick check on the mod info pages and the mod logs didn't reveal anything of the sort. If any advice could be given my way, that would be much appreciated.

### Package

Graphical Interface

### Platform

Windows

**Comment by Bwc9876** [comment]
Hi there! Sorry for the late reply. This sounds like an issue specifically with New Horizons and not the mod manager, could you open an issue [on the New Horizons repo](https://github.com/Outer-Wilds-New-Horizons/new-horizons/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml)?
