### ISSUE TITLE
[Bug Report] Mod manager is unable to detect game installation if it's installed on the SD card on the deck

### ISSUE THREAD

**Issue by Managor** [ow-mods/ow-mod-man#708]
### What Happened?

If I have the game installed in an SD card, the mod manager gives an error `Current game path is not valid: /home/deck/.steam/steam/steamapps/common/Outer Wilds/`

### Package

Graphical Interface

### Platform

Steam Deck

**Comment by Bwc9876** [comment]
Intentional behavior due to FlatPak restrictions on what directories we can access.
