### ISSUE TITLE
[Guide][Steam Deck] Running the manager in Game Mode

### ISSUE THREAD

**Issue by pakoito** [ow-mods/ow-mod-man#71]
### Package

Graphical Interface

### Feature

Super happy that the manager is now compatible with the deck! Please leave where you can be tipped because it's an achievement :D

I've been tinkering with it and it works in desktop mode just okay, but whitescreens on Game Mode with Proton 7 and outright crashes with Proton 8.

Is there any guide to get it working in game mode?

### Platform

Steam Deck

**Comment by pakoito** [comment]
Okay, what I've found so far is that launching the game after installing the mod manager has the Mods menu injected.

**Comment by Bwc9876** [comment]
Hi there! The manager erroring in game mode is a known issue with flatpak, but also it shouldn't need Proton to run the manager itself.

**Comment by Bwc9876** [comment]
I have found what looks like a way to get the manager to work in game mode, seems to be an issue with steam game mode itself but could be outdated. The steps [on this Reddit post](https://www.reddit.com/r/AM2R/comments/yzpskx/comment/ix9x8jo/?utm_source=share&utm_medium=web2x&context=3) might be worth a shot

From what I understand from it the `Target` should be `/usr/bin/flatpak` and the launch options should be `/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=outer-wilds-mod-manager --file-forwarding com.outerwildsmods.owmods_gui`

**Comment by pakoito** [comment]
Gotcha! I found that the Mods are injected even without launching it from OWMM, but for some reason The Vision mod logo wasn't injected on the main screen so I thought it had not loaded.

**Comment by pakoito** [comment]
When adding this as an external program, the target Steam added is all that string plus "@@u" "@@". Removing those doesn't fix it either.

**Comment by Bwc9876** [comment]
Dang ok, I'm gonna try asking the people on the tauri discord if it's a common thing or Smth, will test when I can

**Comment by pakoito** [comment]
If you don't have a deck I'm happy to help with mine.

**Comment by Bwc9876** [comment]
Apologies for the delayed response, I have a deck I can test with but it's been pretty fruitless. The main issue is there's no way to get stdout (unless there's some flatpak flag to log that to a file) because the bug only happens in game mode where I can't get access to a terminal or shell.

**Comment by pakoito** [comment]
Makes sense. I'd fix this in documentation somewhere in the readme, mention that you can only set mods in desktop mode because of technical reasons, but launching the game from Game Mode afterwards will have them enabled correctly.

If people are into mods and have already gone through the other tech bits, they should understand.

**Comment by Bwc9876** [comment]
Okay added the warning to the READMEs and the HELP document, I'm going to close this issue for now but I'll reopen it if I find a way to get it working in game mode

**Comment by pakoito** [comment]
Thanks <3 Anywhere to tip?

**Comment by Bwc9876** [comment]
Yeh my PayPal's here: [https://paypal.me/bwc9876](https://paypal.me/bwc9876), I also have a patreon but don't publish much lol: [https://patreon.com/Bwc9876](https://patreon.com/Bwc9876)

**Comment by Bwc9876** [comment]
Reopening, I *think* I got it working in game mode, see [the flathub PR](https://github.com/flathub/com.outerwildsmods.owmods_gui/pull/28) for merge status
