### ISSUE TITLE
[Bug Report]  cannot install

### ISSUE THREAD

**Issue by threeboi** [ow-mods/ow-mod-man#765]
### What Happened?

whenever i try to install mod manager, theres just a error saying cannot remove older version of owmm, please contact your techinal support.

### Package

Core Package

### Platform

Windows

### Logs

i cant paste logs since this is an installiton issue.

**Comment by Bwc9876** [comment]
Could you try using the NSIS installer instead? https://objects.githubusercontent.com/github-production-release-asset-2e65be/592635586/198ebbb4-ecdb-4584-8de5-bbe4791f0600?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20241024%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20241024T223209Z&X-Amz-Expires=300&X-Amz-Signature=921c94b568a683de3621f17b110070297214a64535d29a3b5050ff6da895714d&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3DOuter.Wilds.Mod.Manager_0.14.2_x64-setup.exe&response-content-type=application%2Foctet-stream
