### ISSUE TITLE
[Bug Report] VR Nomai missing main menu/no controls

### ISSUE THREAD

**Issue by kaladinvegapunk** [ow-mods/ow-mod-man#808]
### What Happened?

Hi! so basically when i try to launch Nomai VR (Through OWML Launcher, Steam or any way) it takes me to the main menu but you cant see any text or menu options and cant see my hands. the music plays but im basically stuck on the title screen. theres only 3 steps to play mods and the rest worked fine before but just this one just refuses to boot up properly. im using default controls, tried verifying install, reinstalling mod manager and the game..
i realize you might only be able to help with the manager itself and not specific mods but i wanted to at least try to see if it was a known issue you might have a solution for. I couldnt find any thread besides 1 discussing it. 

### Package

Graphical Interface

### Platform

Windows

### Logs

the log doesnt spit out any errors just the normal boot up dialogue

**Comment by Raicuparta** [comment]
This isn't an ow-mods bug, should be in the NomaiVR repo instead.
