### ISSUE TITLE
Refresh button label sticks on screen

### ISSUE THREAD

**Issue by misternebula** [ow-mods/ow-mod-man#97]
### What Happened?

"Refresh" label sticks on screen when moving mouse to a different button *while it is still refreshing*.

https://github.com/ow-mods/ow-mod-man/assets/41904486/3fa02cc3-5783-4d4e-bf1c-b44e0fe18b77

### Package

Graphical Interface

### Platform

Windows

**Comment by Bwc9876** [comment]
Linking this for later, looks like pointer events should fix it: https://github.com/mui/material-ui/issues/19742
